### ISSUE TITLE
Broken automated builds on Docker Hub

### ISSUE THREAD

**Issue by OndroNR** [containous/traefik-library-image#17]
Building fails with "Build failed: Dockerfile not found at ./Dockerfile". Problem appeared after v1.4.0-rc1 https://hub.docker.com/r/containous/traefik/builds/

**Comment by OndroNR** [comment]
Maybe this Docker Hub repository is deprecated and we should use https://hub.docker.com/r/library/traefik/ ?

**Comment by emilevauge** [comment]
Oops, indeed, we refactored this repo to add multi arch for the official image. It appears that it messed up the `containous/traefik` build :(
/cc @ldez

**Comment by emilevauge** [comment]
This should be fixed now.

**Comment by OndroNR** [comment]
Thanks a lot. Could you, please, force rebuild of tags?

**Comment by ldez** [comment]
@OndroNR We recommend to use the official Docker image https://hub.docker.com/r/library/traefik/. 

https://hub.docker.com/r/containous/traefik/ is for our testing/experimental/backup images.
