### ISSUE TITLE
Problem downloading traefik:v1.5.4 (actual :latest)

### ISSUE THREAD

**Issue by joariasl** [containous/traefik-library-image#25]
`docker pull traefik:v1.5.4`

> v1.5.4: Pulling from library/traefik
> no matching manifest for linux/amd64 in the manifest list entries

but
`docker pull traefik:v1.5.3`

> v1.5.3: Pulling from library/traefik
> 5d3835484afe: Pull complete 
> 0feefa6e9e49: Pull complete 
> Digest: sha256:d277007b55a8a8d972b1983ef11387d05f719821a2d2e23e8fa06ac5081a302f
> Status: Downloaded newer image for traefik:v1.5.3

**Comment by hermanocabral** [comment]
Build/Docker Build seems to be broken, it happens every now and then unfortunately with not only this repo. From my experience you just have to wait a few for it to go back to normal.

Pro tip: setup a local mirror for docker hub, saves you a lot of pain having images cached locally.

**Comment by emilevauge** [comment]
Indeed, the 1.5.4 release has still not been built. We are on it: https://github.com/docker-library/official-images/pull/4129#issuecomment-373621107

**Comment by emilevauge** [comment]
It finally works :tada:, closing this one then :)
