### ISSUE TITLE
Docker 'experimental' image?

### ISSUE THREAD

**Issue by timoguic** [containous/traefik-library-image#26]
I would like to use the new feature of 301 redirects for HTTP to HTTPS redirections.
However, it looks like the feature is added to the v1.6 milestone. The Docker image currently uses v1.5.4 and does not have it. Is there any chance we can build a Docker image using the 'master' branch?

Thanks.

**Comment by ldez** [comment]
you can use the docker image `containous/traefik` tag `experimental`

**Comment by timoguic** [comment]
How did I not see that?... Thanks a lot.
