### ISSUE TITLE
can't log into container

### ISSUE THREAD

**Issue by gabx** [containous/traefik-library-image#28]
I have a Kubernetes cluster with traffic app installed. I can't log into container from host.
```

# docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
10cfcdca52d9        traefik                               "/traefik"               About an hour ago   Up About an hour                        k8s_mytraffic_mytraffic-7bdc7b7b9d-65m8q_default_acbbab56-49f7-11e8-a9bc-fa163e771c4c_0
# docker exec -ti 10cfcdca52d9 bash 
OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
# docker exec -ti 10cfcdca52d9 /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
```
Host is fedora 27, Kubernetes is 1.10.
I use Rancher to manage the cluster, and when using the Rancher web UI to open a shell inside container, the shell windows open then quickly closes.

**Comment by ldez** [comment]
`traefik` image is a "FROM scratch" image (https://docs.docker.com/develop/develop-images/baseimages/).
If you want to use a shell inside the container, you need to use `traefik-alpine` image.

**Comment by ldez** [comment]
@gabx The git repo of alpine image is here. https://github.com/containous/traefik-library-image/tree/master/alpine

I made a mistake, the image is `traefik:v1.5-alpine`

**Comment by FabianTe** [comment]
I tried using the `alpine` version of 1.6.4 but it still throws:

`OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

**Comment by JoooostB** [comment]
@FabianTe Did you manage to solve this issue? I'm experiencing the same error on my Docker cluster.

**Comment by FabianTe** [comment]
Nope

**Comment by ldez** [comment]
With alpine, you need to use `sh` instead `bash`

```
docker run -it traefik:alpine /bin/sh
```

http://containertutorials.com/alpine/get_started.html

**Comment by guysoft** [comment]
Does not work from kubernetes:
```
kubectl exec -it -n kube-system traefik-7d8cd6f556-j27qx /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
command terminated with exit code 126
```

Anyone with input on that?

**Comment by errm** [comment]
@guysoft are you using the alpine image?

**Comment by guysoft** [comment]
Using:
https://github.com/helm/charts/tree/master/stable/traefik

Aka according to [default ``values.yaml``](https://github.com/helm/charts/blob/master/stable/traefik/values.yaml) ``traefik-1.7.14`` image, so no.

**Comment by errm** [comment]
If you set `imageTag: 1.7.14-alpine` you should be good!

**Comment by guysoft** [comment]
> If you set `imageTag: 1.7.14-alpine` you should be good!

That indeed solves the issue!

**Comment by ManmohitSingh10** [comment]
I am facing the same issue. If I have already installed version 1.85.0, can I change it to 1.7.14-alpine without changing any other configuration?
