### ISSUE TITLE
tag: v1.6.0 not available

### ISSUE THREAD

**Issue by llitfkitfk** [containous/traefik-library-image#29]

**Comment by ldez** [comment]
https://github.com/docker-library/official-images/pull/4304

**Comment by romracer** [comment]
I think for now you can use ```containous/traefik@sha256:74c7e144161a850b648e4a690ad6940c1ef152c7797787e56673c6352846e51c``` but this is not official.  Who knows when the Docker build queue will catch up...

**Comment by llitfkitfk** [comment]
tag: v1.6.0 updated
