### ISSUE TITLE
Configure as automated build on Docker Hub

### ISSUE THREAD

**Issue by adamgoose** [containous/traefik-library-image#3]
It'd be awesome if you could set this up as an automated build on Docker Hub, so that any time you push with a new version, Docker Hub will automatically build the container for you, and we can always have the latest updates! :)

I'd hate to have to build my own container just to get incremental updates.

**Comment by emilevauge** [comment]
That's already the case using this image: https://hub.docker.com/r/containous/traefik/

**Comment by kachkaev** [comment]
And what's the relationship between [`containous/traefik`](https://hub.docker.com/r/containous/traefik/) and [`traefik`](https://hub.docker.com/_/traefik/)? Got a bit confused when saw the second one too.

**Comment by ldez** [comment]
`traefik`  is the official Docker image (https://github.com/docker-library/official-images)
`containous/traefik` is the Docker Image related to our CI.

We recommended to use official Docker image (it's like a LTS) and Containous Docker Image if you want to use our `experimental` tag (it's like nightly).
