### ISSUE TITLE
Remove binaries from repo

### ISSUE THREAD

**Issue by J0WI** [containous/traefik-library-image#47]
This repository is huge and trigges some [quota warnings](https://help.github.com/articles/what-is-my-disk-quota/) on GitHub. Since the official images library does not support multi stage builds, you may consider a similar approach like [the busybox image](https://github.com/docker-library/busybox) and using a builder Dockerfile.

It would be much simpler to just use `ADD` instead of `COPY` (see https://github.com/containous/traefik-library-image/pull/46), but this method does not provide any integrity checks and there is currently no way to make the binary executable on unix hosts (see https://github.com/moby/moby/issues/34819).

**Comment by dduportal** [comment]
As soon as https://github.com/docker-library/official-images/pull/5929 is merged, then we might be able to work on #14 and to fix this.

**Comment by J0WI** [comment]
Are there any plans to clean up the history of this huge repo? :confused:
