### ISSUE TITLE
amd64 image is missing on docker tag 1.7.15

### ISSUE THREAD

**Issue by ViceIce** [containous/traefik-library-image#62]
The `amd64` image is missing on docker hub for all 1.7.15 version tags.

https://hub.docker.com/_/traefik?tab=tags&page=1&name=1.7.15

looks like https://github.com/containous/traefik-library-image/issues/20

**Comment by ldez** [comment]
Take a look here https://github.com/docker-library/official-images/pull/6622#issuecomment-531162235

**Comment by ldez** [comment]
The problem is fixed: https://github.com/docker-library/official-images/pull/6622#issuecomment-531220293
