### ISSUE TITLE
Traefik container broken - command traefik error: field not found, node: address

### ISSUE THREAD

**Issue by lynk81** [containous/traefik-library-image#64]
It looks like my Traefik linux container was updated today and since then my external connectivity is broken and the logs and this same error repeated over and over. 

2019/09/17 04:18:32 command traefik error: field not found, node: address

I have checked with a friend with the same setup and he is getting the same issue. I am running the traefik:latest image on docker on Ubuntu 18.04.

**Comment by lynk81** [comment]
the docker ps command also seems to show it constantly rebooting. 

6a68b7b3a001        traefik:latest               "/entrypoint.sh trae…"   51 minutes ago      Restarting (1) 23 seconds ago

**Comment by mmatur** [comment]
@lynk81 Friends don't let Friends use `latest` tag ;)

You have to change the image to `traefik:v1.7` instead of `traefik:latest`.

**Comment by lynk81** [comment]
changed the tag in docker compose as suggested and fixed :)
