### ISSUE TITLE
latest docker image does not start, stuck at create

### ISSUE THREAD

**Issue by Ga22be** [containous/traefik-library-image#65]
Installed the latest version and was met with the error: 

> ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/traefik\": stat /traefik: no such file or directory": unknown")

I do not exactly know what that means but going back to 1.7 fixed the issue.

**Comment by ldez** [comment]
the `latest` tag point to the Traefik v2.0.

Duplicate #64

**Comment by dduportal** [comment]
@Ga22be it looks like you're overriding the default entrypoint/cmd of the image. The traefik binary is located in `/usr/local/bin/traefik` (and not `/traefik`)  anymore with version 2.0: https://github.com/containous/traefik-library-image/blob/9954ed014366d9def23b3d695e38cad339ff14bc/alpine/Dockerfile#L14.
