### ISSUE TITLE
DockerHub does not have the v2.0.2 AMD64 version

### ISSUE THREAD

**Issue by lx0758** [containous/traefik-library-image#68]
DockerHub does not have the v2.0.2 AMD64 version
![TIM截图20191010110808](https://user-images.githubusercontent.com/9001145/66536052-43dc5380-eb4e-11e9-9f17-74afe00d2291.jpg)

**Comment by mmatur** [comment]
Hi @lx0758,

![image](https://user-images.githubusercontent.com/1776972/66544868-9cedbc80-eb39-11e9-952d-83863f8686df.png)

It seems to ok now. 

It's probably due to a delay during the build on docker platform.

**Comment by huangjunwen** [comment]
Happen again for v2.0.5

![Screenshot from 2019-11-15 09-07-27](https://user-images.githubusercontent.com/720086/68908872-8a455380-0787-11ea-855a-71cc00efc397.png)

**Comment by ldez** [comment]
It always happen because the images are built by Docker, we do not control the way they are published.
