### ISSUE TITLE
Add 'beta' / 'development' tag to latest (beta/development) image

### ISSUE THREAD

**Issue by derphilipp** [containous/traefik-library-image#7]
It would be nice to be able to use the latest (non-stable) built of traefik; Therefore I suggest a tag that is always attached to the very latest non-stable build.

**Comment by vdemeester** [comment]
I think it's `containous/traefik:latest` (always deployed anytime a commit lands in master). It can't be done with official image (it would require too much update).
/cc @emilevauge

**Comment by derphilipp** [comment]
Well I would like to have the (unstable) RC releases, but not all and every single commit version; Is that possible?

**Comment by vdemeester** [comment]
RC release are also available 👼 `traefik:v1.2.0-rc1` for example

**Comment by derphilipp** [comment]
Yes, but what I am missing is a tag that constantly updates to the latest rc release;

**Comment by vdemeester** [comment]
@derphilipp oh I see 😅 @emilevauge doable ? 👼

**Comment by davidwindell** [comment]
I'd love a `nightly` release, pretty please

**Comment by ldez** [comment]
@derphilipp you can use the `containous/traefik:experimental` tag

**Comment by derphilipp** [comment]
Awesome! Thank you very much.
