### ISSUE TITLE
Problem to forward requests when container has more than one network

### ISSUE THREAD

**Issue by vambertojr** [containous/traefik-library-image#82]
Hello,
I'm having problems to forward requests when container has more than one network.
In the docker-compose file, I create 2 networks: frontend for apps and backend for database. The container that is causing me problems is the dspace that has the 2 networks. When I leave only the frontend network the routing of the traefik works.
I've tried using the options "providers.docker.network=frontend" and "traefik.docker.network=frontend" but still don't work.

[docker-compose.txt](https://github.com/containous/traefik-library-image/files/4767872/docker-compose.txt)

**Comment by ldez** [comment]
Hello,

it's not the right place to ask a question.

You can join the community forum https://community.containo.us/
