### ISSUE TITLE
LetsEncrypt isn't working correctly

### ISSUE THREAD

**Issue by joshs85** [containous/traefik-library-image#86]
Using version: latest docker (2.3.6)

Error I'm getting both when renewing and requesting new: 
legolog: [INFO] retry due to: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/authz-v3/REDACTED:: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: \"REDACTED\", url: 
legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/REDACTED
Unable to obtain ACME certificate for domains \"REDACTED\": unable to generate a certificate for the domains [REDACTED]: error: one or more domains had a problem:\n[REDACTED] time limit exceeded: last error: NS ns-1153.awsdns-16.org. returned REFUSED for _acme-challenge.REDACTED.\n" rule="Host(`REDACTED`)" providerName=default.acme routerName=server@docker

Configuration:
[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "REDACTED"
      storage = "/etc/traefik/acme/acme.json"
      [certificatesResolvers.default.acme.dnsChallenge]
        provider = "route53"
        delayBeforeCheck = "3m"
        resolvers = ["192.168.3.1:53"]

**Comment by ldez** [comment]
Hello,

It's not the right repository.

I recommend explaining your problem in the forum https://community.traefik.io/
